name: "smoke-screen-tests"
on:
  push:
    branches-ignore:
      - master

jobs:
  sst:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: |
        npm install
        npm test
